apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: application
  namespace: argocd
spec:
  description: "Projeto para aplicações implantadas via Helm"
  sourceRepos:
    - ssh://git@gitea-ssh.gitea.svc.cluster.local:2222/mateusmullerme/helm-applications.git
  destinations:
    - namespace: api
      server: https://kubernetes.default.svc
    - namespace: argocd
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceBlacklist: []
