apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: homelab-pool
  namespace: metallb-system
spec:
  addresses:
  - 172.17.0.50-172.17.0.90
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: home-adversiment
  namespace: metallb-system
spec:
  ipAddressPools:
  - homelab-pool