apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: argo-cd
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd # Namespace for ArgoCD
  # --- Multiple Sources ---
  sources:
    # 1) Public Chart
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: "8.0.17"
      helm:
        releaseName: argocd
        valueFiles:
          - $values/cicd/values/argocd/argocd-values.yaml
    # 2) Private Repo with custom values
    - repoURL: hhttps://github.com/blackorbitcode/argocd-devops.git
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      # allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "300s"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      # Server-Side Apply for better conflict resolution
      - PruneLast=true            # Prune resources after the sync operation
      - ApplyOutOfSyncOnly=true   # Only apply changes if the resource is out of sync