apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-projects
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: "https://github.com/patrickmanzooo/arg.git"
    targetRevision: "main"
    path: "devops-complete-ci-cd-projetct/argocd/argocd-appprojects" # <- Pasta onde armazenará AppProject YAMLs
    directory:
      recurse: true
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      # allowEmpty: false
    retry:
      limit: 5  # Número máximo de tentativas
      backoff:
        duration: "30s"  # Tempo entre tentativas
        factor: 2  # Multiplicador do tempo de espera
        maxDuration: "300s"  # Tempo máximo de espera
    syncOptions:
      - CreateNamespace=true