apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: jenkins-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: jenkins-project
  destination:
    server: https://kubernetes.default.svc
    namespace: jenkins # Namespace for Jenkins
  # --- Multiple Sources ---
  sources:
    # 1) Public Chart
    - repoURL: https://charts.jenkins.io
      chart: jenkins
      targetRevision: "5.8.56"
      helm:
        valueFiles:
          - $values/devops-complete-ci-cd-projetct/values/jenkins/jenkins-values.yaml
    # 2) Private Repo with custom values
    - repoURL: https://github.com/patrickmanzo/Projects.git
      targetRevision: main
      ref: values
  syncPolicy:
    # automated:
      # selfHeal: true
      # prune: true
      # allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "300s"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      # Server-Side Apply for better conflict resolution
      - PruneLast=true            # Prune resources after the sync operation
      - ApplyOutOfSyncOnly=true   # Only apply changes if the resource is out of sync