apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarqube-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: sonarqube-project
  destination:
    server: https://kubernetes.default.svc
    namespace: sonarqube # Namespace for SonarQube
  # --- Multiple Sources ---
  sources:
    # 1) Public Chart
    - repoURL: https://SonarSource.github.io/helm-chart-sonarqube
      chart: sonarqube
      targetRevision: "2025.3.0"
      helm:
        valueFiles:
          - $values/cicd/values/sonarqube/sonarqube-values.yaml
    # 2) Private Repo with custom values
    - repoURL: https://github.com/blackorbitcode/argocd-devops.git
      targetRevision: main
      ref: values
  syncPolicy:
    # automated:
      # selfHeal: true
      # prune: true
      # allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "300s"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true      # Server-Side Apply for better conflict resolution
      - PruneLast=true            # Prune resources after the sync operation
      - ApplyOutOfSyncOnly=true   # Only apply changes if the resource is out of sync