apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor-application
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: harbor-project
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor # Namespace for Harbor
  # --- Multiple Sources ---
  sources:
    # 1) Public Chart
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.17.0"
      helm:
        valueFiles:
          - $values/cicd/values/harbor/harbor-values.yaml
    # 2) Private Repo with custom values
    - repoURL: https://github.com/blackorbitcode/argocd-devops.git
      targetRevision: main
      ref: values
  syncPolicy:
    # automated:
      # selfHeal: true
      # prune: true
      # allowEmpty: false
    retry:
      limit: 5
      backoff:
        duration: "30s"
        factor: 2
        maxDuration: "300s"
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # Server-Side Apply for better conflict resolution
      - PruneLast=true # Prune resources after the sync operation
      - ApplyOutOfSyncOnly=true # Only apply changes if the resource is out of sync