apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: setup-hosts
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: https://github.com/blackorbitcode/argocd-devops.git
    targetRevision: main
    path: cicd/manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ApplyOutOfSyncOnly=true
      - PruneLast=true