apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sonarqube-project
  namespace: argocd
spec:
  description: Projeto Argo CD para SonarQube
  sourceRepos:
    - 'https://SonarSource.github.io/helm-chart-sonarqube'
    - 'https://github.com/blackorbitcode/argocd-devops.git'
  destinations:
    - namespace: sonarqube
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'