apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gitea-project
  namespace: argocd
spec:
  description: Projeto Argo CD para Gitea
  sourceRepos:
    - 'https://dl.gitea.io/charts'
    - 'https://github.com/patrickmanzo/Projects.git'
  destinations:
    - namespace: gitea
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'