apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: cert-manager-project
  namespace: argocd
spec:
  description: Projeto exclusivo para o cert-manager
  sourceRepos:
    - 'https://charts.jetstack.io'
    - 'https://github.com/patrickmanzo/Projects.git'
  destinations:
    - namespace: cert-manager
      server: 'https://kubernetes.default.svc'
    - namespace: kube-system
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'