apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: harbor-project
  namespace: argocd
spec:
  description: Projeto Argo CD para Harbor
  sourceRepos:
    - 'https://helm.goharbor.io'
    - 'https://github.com/patrickmanzo/Projects.git'
  destinations:
    - namespace: harbor
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'